# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PizzaMe' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'


  # Pods for PizzaMe

  target 'PizzaMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PizzaMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
